import Foundation
import SwiftUI
import Combine

@MainActor
final class DailySummaryService: ObservableObject {
    @Published var isGenerating = false
    @Published var progressMessage = ""
    @Published var summaryText = ""
    
    // Stats of the logs to be summarized
    @Published var logCount = 0
    @Published var tokenCount = 0
    @Published var modelCount = 0
    @Published var toolCount = 0
    
    struct LogPeriodStats {
        var logCount: Int = 0
        var tokenCount: Int = 0
        var activeModels: Set<String> = []
        var activeTools: Set<String> = []
    }
    
    func calculateStats(for logs: [ParsedLog]) -> LogPeriodStats {
        var stats = LogPeriodStats()
        stats.logCount = logs.count
        for log in logs {
            stats.tokenCount += log.totalTokens ?? 0
            if let m = log.modelName, !m.isEmpty {
                stats.activeModels.insert(m)
            }
            if let client = log.metadata["client"], !client.isEmpty {
                stats.activeTools.insert(client)
            }
        }
        return stats
    }
    
    func generateSummary(
        logs: [ParsedLog],
        provider: String,
        baseUrl: String,
        model: String,
        apiKey: String
    ) async {
        guard !logs.isEmpty else {
            self.summaryText = "今天没有模型交互日志，无法生成复盘。"
            return
        }
        
        self.isGenerating = true
        self.progressMessage = "正在整理日志数据..."
        
        // Calculate and update stats locally for immediate display
        let stats = calculateStats(for: logs)
        self.logCount = stats.logCount
        self.tokenCount = stats.tokenCount
        self.modelCount = stats.activeModels.count
        self.toolCount = stats.activeTools.count
        
        // Format the logs
        let formattedLogs = formatLogsForLLM(logs)
        
        self.progressMessage = "正在向 AI 发起请求并撰写复盘报告..."
        
        do {
            let summary = try await sendLLMRequest(
                logsText: formattedLogs,
                provider: provider,
                baseUrl: baseUrl,
                model: model,
                apiKey: apiKey
            )
            self.summaryText = summary
        } catch {
            self.summaryText = "生成失败: \(error.localizedDescription)\n\n请检查模型服务配置（如 Ollama 是否启动、API Key/Base URL 是否正确）。"
        }
        
        self.isGenerating = false
        self.progressMessage = ""
    }
    
    private func formatLogsForLLM(_ logs: [ParsedLog]) -> String {
        // 1. Exclude logs generated by this program's own agent tasks or other background agents (like pi)
        let filtered = logs.filter { log in
            let isBgAgent = log.provider == .antigravity || 
                            log.metadata["client"] == "antigravity" || 
                            log.sourceFile.lowercased().contains("antigravity") ||
                            log.provider == .pi ||
                            log.metadata["client"] == "pi" ||
                            log.sourceFile.lowercased().contains("pi")
            return !isBgAgent
        }
        
        // 2. Prioritize manual interactive tools (copilot, cursor, cline, warp, claude-code)
        // so that if we have too many logs, we keep direct developer actions first.
        let manualClients = ["copilot", "cursor", "cline", "claude-code", "warp", "vscode", "claude-desktop", "claude_desktop"]
        
        func isManual(_ log: ParsedLog) -> Bool {
            let client = log.metadata["client"]?.lowercased() ?? ""
            let source = log.sourceFile.lowercased()
            let providerStr = log.provider?.rawValue.lowercased() ?? ""
            
            if manualClients.contains(where: { client.contains($0) || source.contains($0) || providerStr.contains($0) }) {
                return true
            }
            return false
        }
        
        let manualLogs = filtered.filter { isManual($0) }
        let automatedLogs = filtered.filter { !isManual($0) }
        
        // Prioritize manual logs up to 150, then fill remaining slots with automated logs
        var selectedLogs: [ParsedLog] = []
        if manualLogs.count <= 150 {
            selectedLogs.append(contentsOf: manualLogs)
            let remainingSlots = 150 - selectedLogs.count
            if remainingSlots > 0 {
                selectedLogs.append(contentsOf: automatedLogs.suffix(remainingSlots))
            }
        } else {
            selectedLogs.append(contentsOf: manualLogs.suffix(150))
        }
        
        let logsToProcess = selectedLogs.sorted { $0.timestamp < $1.timestamp }
        
        var text = ""
        let formatter = DateFormatter()
        formatter.dateFormat = "HH:mm:ss"
        
        for (index, log) in logsToProcess.enumerated() {
            let timeStr = formatter.string(from: log.timestamp)
            let provStr = log.provider?.displayName ?? "Unknown"
            let modelStr = log.modelName ?? "Unknown"
            let clientStr = log.metadata["client"] ?? "Unknown"
            
            text += "=== Log #\(index + 1) [Time: \(timeStr)] [Provider: \(provStr)] [Model: \(modelStr)] [Client: \(clientStr)] ===\n"
            
            var hasContent = false
            if let prompt = log.prompt, !prompt.isEmpty {
                let trimmedPrompt = prompt.count > 800 ? String(prompt.prefix(800)) + "...(已截断)" : prompt
                text += "Prompt:\n\(trimmedPrompt)\n"
                hasContent = true
            }
            
            if let response = log.response, !response.isEmpty {
                let trimmedResponse = response.count > 800 ? String(response.prefix(800)) + "...(已截断)" : response
                text += "Response:\n\(trimmedResponse)\n"
                hasContent = true
            }
            
            // If both prompt and response are empty, output the activity label if present
            if !hasContent, let label = log.metadata["label"], !label.isEmpty {
                text += "Activity: \(label)\n"
            }
            
            text += "\n"
        }
        
        // If length exceeds 80000 characters, truncate
        if text.count > 80000 {
            text = String(text.prefix(80000)) + "\n...(由于上下文长度限制，后续部分已被丢弃)\n"
        }
        
        return text
    }
    
    private func sendLLMRequest(
        logsText: String,
        provider: String,
        baseUrl: String,
        model: String,
        apiKey: String
    ) async throws -> String {
        let systemPrompt = """
你是一个高效且敏锐的个人工作助理，专门负责根据用户的本地 AI 模型交互日志生成一份精美的“今日复盘”报告。
用户的日志包含了今天他们通过 VS Code Copilot、Cursor、Cline、Claude Code、Warp 等工具与各种 AI 模型交互的所有记录。
请对这些日志进行聚类和深度分析，特别关注并识别用户在 VS Code Copilot 中的交互场景（通常标记为 Client: vscode 或 Provider: GitHub Copilot，如重构设计、RAG流程拆解、测试编写等）和 Warp 终端中的活动事件（通常标记为 Client: warp），然后生成一份结构化、内容充实且极具视觉美感的 Markdown 复盘报告。

报告应包含以下几个模块：
1. 【今日工作概览】 (Summary)：用一两句生动而精炼的话总结今天的工作重点、主要性质或主旋律。
2. 【核心任务与进度】 (Key Tasks & Progress)：分析用户在日志中尝试解决的几大任务/问题/项目。针对每个任务，给出：
   - 任务名称与目标（用加粗表示，例如 `**开发/重构模块 X**`）
   - 技术实现路径与解决策略，特别结合 VS Code Copilot、Claude Code 等交互过程来梳理技术细节
   - 该任务当前的进度状态（例如：已解决、开发中、排查中）
3. 【模型与工具使用分析】 (Models & Tools Analysis)：简要列举并归纳今天最常使用的模型（如 Claude, GPT, DeepSeek）和客户端工具（例如明确提及 VS Code Copilot、Cursor 或 Warp 终端工具）。分析它们在这个过程中扮演的角色。
4. 【技术亮点与收获】 (Insights & Learnings)：分析用户在今天写代码或交互中体现出的技术亮点，遇到了哪些典型的 Bug、报错，以及是如何解决或推进的。
5. 【下一步展望与建议】 (Next Steps)：基于今天的进度，给出下一步的合理建议或接下来可能需要重点处理的待办事项。

注意事项：
- 必须使用中文生成报告。
- 风格专业、精炼，且富有条理，段落分明，合理运用 markdown 的标题、列表和加粗等。
- 报告中若包含代码文件名、函数名或技术栈，请使用行内代码格式标注。
- 报告必须完全基于用户提供的真实日志，请勿虚构任何用户未做过的事。
"""

        // Resolve base URL
        let finalUrlString = try resolveUrl(provider: provider, baseUrl: baseUrl)
        
        guard let url = URL(string: finalUrlString) else {
            throw NSError(domain: "DailySummary", code: -1, userInfo: [NSLocalizedDescriptionKey: "无效的请求 URL: \(finalUrlString)"])
        }
        
        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        
        // Set API Keys
        if !apiKey.isEmpty {
            if provider == "anthropic" {
                request.setValue(apiKey, forHTTPHeaderField: "x-api-key")
                request.setValue("2023-06-01", forHTTPHeaderField: "anthropic-version")
            } else {
                request.setValue("Bearer \(apiKey)", forHTTPHeaderField: "Authorization")
            }
        }
        
        let userContent = "以下是我的模型交互日志，请为我分析并生成复盘报告：\n\n\(logsText)"
        
        let requestBody: Data
        if provider == "anthropic" {
            let bodyObj: [String: Any] = [
                "model": model,
                "max_tokens": 4000,
                "system": systemPrompt,
                "messages": [
                    ["role": "user", "content": userContent]
                ]
            ]
            requestBody = try JSONSerialization.data(withJSONObject: bodyObj)
        } else {
            let bodyObj: [String: Any] = [
                "model": model,
                "messages": [
                    ["role": "system", "content": systemPrompt],
                    ["role": "user", "content": userContent]
                ],
                "stream": false
            ]
            requestBody = try JSONSerialization.data(withJSONObject: bodyObj)
        }
        
        request.httpBody = requestBody
        
        let (data, response) = try await URLSession.shared.data(for: request)
        
        guard let httpResponse = response as? HTTPURLResponse else {
            throw NSError(domain: "DailySummary", code: -1, userInfo: [NSLocalizedDescriptionKey: "未能获得有效的 HTTP 响应"])
        }
        
        guard httpResponse.statusCode == 200 else {
            let errorText = String(data: data, encoding: .utf8) ?? "未知错误"
            throw NSError(domain: "DailySummary", code: httpResponse.statusCode, userInfo: [NSLocalizedDescriptionKey: "服务器返回错误 (\(httpResponse.statusCode)): \(errorText)"])
        }
        
        if provider == "anthropic" {
            guard let json = try JSONSerialization.jsonObject(with: data) as? [String: Any],
                  let content = json["content"] as? [[String: Any]],
                  let firstContent = content.first,
                  let text = firstContent["text"] as? String else {
                throw NSError(domain: "DailySummary", code: -1, userInfo: [NSLocalizedDescriptionKey: "解析 Anthropic 响应失败"])
            }
            return text
        } else {
            guard let json = try JSONSerialization.jsonObject(with: data) as? [String: Any],
                  let choices = json["choices"] as? [[String: Any]],
                  let firstChoice = choices.first,
                  let message = firstChoice["message"] as? [String: Any],
                  let text = message["content"] as? String else {
                throw NSError(domain: "DailySummary", code: -1, userInfo: [NSLocalizedDescriptionKey: "解析 OpenAI/Ollama 响应失败"])
            }
            return text
        }
    }
    
    private func resolveUrl(provider: String, baseUrl: String) throws -> String {
        var finalUrlString = baseUrl.trimmingCharacters(in: .whitespacesAndNewlines)
        if finalUrlString.isEmpty {
            switch provider {
            case "ollama": finalUrlString = "http://127.0.0.1:11434"
            case "lmstudio": finalUrlString = "http://127.0.0.1:1234"
            case "vllm": finalUrlString = "http://127.0.0.1:8000"
            case "deepseek": finalUrlString = "https://api.deepseek.com"
            case "openai": finalUrlString = "https://api.openai.com"
            case "anthropic": finalUrlString = "https://api.anthropic.com"
            default: throw NSError(domain: "DailySummary", code: -1, userInfo: [NSLocalizedDescriptionKey: "缺少有效的 Base URL"])
            }
        }
        
        func appendOpenAIChatCompletions(to baseUrl: String) -> String {
            var url = baseUrl
            if url.hasSuffix("/") {
                url = String(url.dropLast())
            }
            if url.hasSuffix("/v1") {
                return "\(url)/chat/completions"
            } else if url.hasSuffix("/chat/completions") {
                return url
            } else {
                if !url.contains("/v1") && !url.contains("/chat/completions") {
                    return "\(url)/v1/chat/completions"
                } else if url.contains("/v1") && !url.contains("/chat/completions") {
                    return "\(url)/chat/completions"
                }
                return url
            }
        }
        
        if provider == "anthropic" {
            var url = finalUrlString
            if url.hasSuffix("/") {
                url = String(url.dropLast())
            }
            if !url.contains("/v1/messages") && !url.contains("/messages") {
                finalUrlString = "\(url)/v1/messages"
            } else {
                finalUrlString = url
            }
        } else {
            finalUrlString = appendOpenAIChatCompletions(to: finalUrlString)
        }
        
        return finalUrlString
    }
    
    func testConnection(
        provider: String,
        baseUrl: String,
        model: String,
        apiKey: String
    ) async -> (success: Bool, message: String) {
        do {
            let finalUrlString = try resolveUrl(provider: provider, baseUrl: baseUrl)
            guard let url = URL(string: finalUrlString) else {
                return (false, "无效的 URL: \(finalUrlString)")
            }
            
            var request = URLRequest(url: url)
            request.httpMethod = "POST"
            request.setValue("application/json", forHTTPHeaderField: "Content-Type")
            request.timeoutInterval = 10
            
            if !apiKey.isEmpty {
                if provider == "anthropic" {
                    request.setValue(apiKey, forHTTPHeaderField: "x-api-key")
                    request.setValue("2023-06-01", forHTTPHeaderField: "anthropic-version")
                } else {
                    request.setValue("Bearer \(apiKey)", forHTTPHeaderField: "Authorization")
                }
            }
            
            let requestBody: Data
            if provider == "anthropic" {
                let bodyObj: [String: Any] = [
                    "model": model,
                    "max_tokens": 1,
                    "messages": [
                        ["role": "user", "content": "ping"]
                    ]
                ]
                requestBody = try JSONSerialization.data(withJSONObject: bodyObj)
            } else {
                let bodyObj: [String: Any] = [
                    "model": model,
                    "messages": [
                        ["role": "user", "content": "ping"]
                    ],
                    "max_tokens": 1,
                    "stream": false
                ]
                requestBody = try JSONSerialization.data(withJSONObject: bodyObj)
            }
            
            request.httpBody = requestBody
            
            let (data, response) = try await URLSession.shared.data(for: request)
            
            guard let httpResponse = response as? HTTPURLResponse else {
                return (false, "未能获得有效的 HTTP 响应")
            }
            
            if httpResponse.statusCode == 200 {
                return (true, "连接成功！配置正确。")
            } else {
                let errorText = String(data: data, encoding: .utf8) ?? "未知错误"
                return (false, "连接失败 (状态码 \(httpResponse.statusCode)): \(errorText)")
            }
        } catch {
            return (false, "连接异常: \(error.localizedDescription)")
        }
    }
}
